# Site
repository: filipef101/filipef101.github.io
favicon: images/favicon.ico
darkmode: false
# Personal info
name: Filipe Fernandes
title: Senior Engineer
email: filipef101@sapo.pt
# website: https://filas.me

# Social links
# twitter_username: zilipef101
github_username: filipef101
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: filipef101
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
gtag: UA-159384073-1
gtm: true
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Filipe and I'm from Portugal.

  Senior Engineer with 8+ years of experience specializing in React Native mobile development. 
  I've led critical technical initiatives in fintech and healthcare sectors, with a strong emphasis 
  on code quality, security, and maintainability. Passionate about full-stack development, system design, 
  and creating exceptional developer experiences through mentoring and best practices.
  Expert in TypeScript, mobile DevOps, and cross-platform development.

  I am most skilled in: <mark>React Native</mark>, <mark>TypeScript</mark> and <mark>Mobile DevOps</mark> 

  Currently exploring Swift beyond mobile development while diving into other cross-platform frameworks like Kotlin Multiplatform and AvaloniaUI 

  When I'm not coding, you'll find me engaged in philosophical debates with my cat or tinkering with home automation projects.

  I speak native <mark>Portuguese</mark>, fluent <mark>English</mark> and baguette French.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Skills

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Nature & Sightseeing
   - Home automation
   - Gaming
   - Movies

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
